name: lolstar-server
app: node@16
options:
  env:
    - name: NODE_ENV
      value: production
    - name: SHADOW_DATABASE_URL
      value: mysql://5fbpqf73h8lykay07ss1:pscale_pw_9Mzr47NanvHohWxqJ1f6yCjzO1uHo5qfMksV7dzQs1F@aws.connect.psdb.cloud/lolstar-db?sslaccept=strict
    - name: DATABASE_URL
      value: mysql://5fbpqf73h8lykay07ss1:pscale_pw_9Mzr47NanvHohWxqJ1f6yCjzO1uHo5qfMksV7dzQs1F@aws.connect.psdb.cloud/lolstar-db?sslaccept=strict
    - name: PASSWORD
      value: a102030
    - name: ACCESS_SECRET_KEY
      value: asjdklwjijqildjkalsjdliwjaliajdskl
    - name: REFRESH_SECRET_KEY
      value: aasdwqqqsddllaosdkso
    - name: ESPORTS_URL
      value: https://game.naver.com/esports/League_of_Legends/record/lck/player/lck_2023_summer
    - name: ESPORTS_NEWS
      value: https://game.naver.com/esports/League_of_Legends/stoveleague/lck2023?type=news
    - name: NAVER_ID
      value: 8y2biYDOLeKgBKRNhi9h
    - name: NAVER_SECRET
      value: 8QsCrP62Qg
    - name: NAVER_URL
      value: https://openapi.naver.com/v1/search/news.json
  build: npm run build
  start: npm run start
  ports: '3000'
context:
  git:
    url: https://github.com/dwhddnjs/lolstar-server.git
    branch: main
  preset: nest.js
